Add {rejectUnauthorized :boolean} to ssl type
InnovA2/winston-pg pull request #4
Opened 2024-04-02 09:53 UTC by toddhalfpenny

The current interface for `PostgresOptions` does not support everything.
This PR updates the `ssl` property to support an object, e,g, ` {rejectUnauthorized :boolean }`

2024-04-08 20:33 UTC, WaZeR-Adrien requested changes

2024-04-08 20:33 UTC, WaZeR-Adrien commented on src/postgres-options.ts
> +    ssl?: {rejectUnauthorized :boolean } | boolean;
Hello, just a small standard and I approve this PR
```suggestion
    ssl?: { rejectUnauthorized: boolean } | boolean;
```

2024-04-09 09:36 UTC, toddhalfpenny commented
Wonderful :)

2024-04-15 21:56 UTC, merged

2024-04-15 22:03 UTC, WaZeR-Adrien commented
Hi, it's released in 1.3.2 :)